version: '3'

services:
  bookdb:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: uporabnik
      MONGO_INITDB_ROOT_PASSWORD: geslo
    ports:
      - "27017:27017"
  bookapi:
    image: jurek01/book_api:latest
    depends_on:
      - bookdb
    ports:
      - "8088:8080"
    environment:
      MONGO_CONNECTION_STRING: "mongodb://uporabnik:geslo@bookdb:27017"
    restart: always

  borrowing:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:

      MONGO_INITDB_ROOT_USERNAME: uporabnik
      MONGO_INITDB_ROOT_PASSWORD: geslo
    ports:
      - "27000:27017"

      #colection name: 
  user:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: uporabnik
      MONGO_INITDB_ROOT_PASSWORD: geslo
    ports:
      - "27018:27017"

  user_api:
    image: jurek01/user_api:latest
    environment:
      MONGO_CONNECTION_STRING: "mongodb://uporabnik:geslo@user:27017"
      MONGO_DATABASE: "bookshare"
    ports:
      - "8080:8080"
      
  activemq:
    image: webcenter/activemq:latest
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WRITE_LOGIN: writer
      ACTIVEMQ_WRITE_PASSWORD: writer
      ACTIVEMQ_READ_LOGIN: reader
      ACTIVEMQ_READ_PASSWORD: reader      
    ports:
      - "8161:8161" # Admin console
      - "61616:61616" # JMS
      - "5672:5672" # AMQP
      - "61613:61613" # STOMP

  borrowing_api:
    image: jurek01/borrowing_api:latest
    depends_on:
      - borrowing
      - activemq
    ports:
      - "8089:8080"
    environment:
      MONGO_CONNECTION_STRING: "mongodb://uporabnik:geslo@borrowing:27017"
      AMQP_HOST: "activemq"
    restart: always

  web_api:
    image: jurek01/web_api
    environment:      
      BOOK_API: http://bookapi:8080/book
      BORROWING_API: http://borrowing_api:8080/borrowings/  
      USER_API: http://user_api:8080/user/
      ASPNETCORE_ENVIRONMENT: Development           
    ports:
      - "1000:8080" # STOMP


  mobile_api:
    image: jurek01/mobile_api
    environment:      
      BOOK_API: http://bookapi:8080/book
      BORROWING_API: http://borrowing_api:8080/borrowings/  
      USER_API: http://user_api:8080/user/
      
      ASPNETCORE_ENVIRONMENT: Development           
    ports:
      - "2000:8080" # STOMP

  auth:
    image: auth
    ports:
      - "2001:3000"
    environment:
      NODE_ENV: production
  web_frontend:
    image: front_end
    ports:
      - "2003:80"
    environment:
      URL_API: http://web_api:1000

  stats:
    image: jurek01/stats
    ports:
      - "2004:3000"
    
  stats_db:
    image: mongo:5.0.25
    ports:
      - "30002:27017"
      

