# Uporabi Node.js s sliko
FROM node:14

# Nastavi delovni imenik v kontejnerju
WORKDIR /usr/src/app

# Kopiraj odvisnosti package.json in package-lock.json
COPY package*.json ./

# Namesti odvisnosti
RUN npm install

# Kopiraj preostanek kode v delovni imenik v kontejnerju
COPY . .

# Izpostavi vrata, na katerih bo aplikacija poslušala
EXPOSE 3000

# Ukaz za zagon aplikacije
CMD ["node", "app.js"]
