version: '3'

services:
  user:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: uporabnik
      MONGO_INITDB_ROOT_PASSWORD: geslo
    ports:
      - "27018:27017"
  user_api:
    image: jurek01/user_api:latest
    environment:
      MONGO_CONNECTION_STRING: "mongodb://uporabnik:geslo@user:27017"
      MONGO_DATABASE: "bookshare"
    ports:
      - "8080:8080"

networks:
  default:
    name: moje-omrežje